// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: AppInterface.proto at 711:1
package com.yijianyi.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * 	护士MMSE评估
 */
public final class AddInsureAssessMMSERsp extends Message<AddInsureAssessMMSERsp, AddInsureAssessMMSERsp.Builder> {
  public static final ProtoAdapter<AddInsureAssessMMSERsp> ADAPTER = new ProtoAdapter_AddInsureAssessMMSERsp();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_INSURENO = "";

  public static final Long DEFAULT_SCORE = 0L;

  /**
   * 订单唯一id
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String insureNO;

  /**
   * 分数
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long score;

  public AddInsureAssessMMSERsp(String insureNO, Long score) {
    this(insureNO, score, ByteString.EMPTY);
  }

  public AddInsureAssessMMSERsp(String insureNO, Long score, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.insureNO = insureNO;
    this.score = score;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.insureNO = insureNO;
    builder.score = score;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AddInsureAssessMMSERsp)) return false;
    AddInsureAssessMMSERsp o = (AddInsureAssessMMSERsp) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(insureNO, o.insureNO)
        && Internal.equals(score, o.score);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (insureNO != null ? insureNO.hashCode() : 0);
      result = result * 37 + (score != null ? score.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (insureNO != null) builder.append(", insureNO=").append(insureNO);
    if (score != null) builder.append(", score=").append(score);
    return builder.replace(0, 2, "AddInsureAssessMMSERsp{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<AddInsureAssessMMSERsp, Builder> {
    public String insureNO;

    public Long score;

    public Builder() {
    }

    /**
     * 订单唯一id
     */
    public Builder insureNO(String insureNO) {
      this.insureNO = insureNO;
      return this;
    }

    /**
     * 分数
     */
    public Builder score(Long score) {
      this.score = score;
      return this;
    }

    @Override
    public AddInsureAssessMMSERsp build() {
      return new AddInsureAssessMMSERsp(insureNO, score, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_AddInsureAssessMMSERsp extends ProtoAdapter<AddInsureAssessMMSERsp> {
    ProtoAdapter_AddInsureAssessMMSERsp() {
      super(FieldEncoding.LENGTH_DELIMITED, AddInsureAssessMMSERsp.class);
    }

    @Override
    public int encodedSize(AddInsureAssessMMSERsp value) {
      return (value.insureNO != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.insureNO) : 0)
          + (value.score != null ? ProtoAdapter.UINT64.encodedSizeWithTag(2, value.score) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, AddInsureAssessMMSERsp value) throws IOException {
      if (value.insureNO != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.insureNO);
      if (value.score != null) ProtoAdapter.UINT64.encodeWithTag(writer, 2, value.score);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public AddInsureAssessMMSERsp decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.insureNO(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.score(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public AddInsureAssessMMSERsp redact(AddInsureAssessMMSERsp value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
