// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: AppInterface.proto at 584:1
package com.yijianyi.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class AddInsureRsp extends Message<AddInsureRsp, AddInsureRsp.Builder> {
  public static final ProtoAdapter<AddInsureRsp> ADAPTER = new ProtoAdapter_AddInsureRsp();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_INSURENO = "";

  public static final String DEFAULT_LASTASSESSTIME = "";

  public static final Integer DEFAULT_SCORE = 0;

  public static final Integer DEFAULT_STATUS = 0;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String insureNO;

  /**
   * 上次自评时间
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String lastAssessTime;

  /**
   * 上次自评分数 -1 即没有自评过 -2有自评，且不需要自评，直接去详情
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer score;

  /**
   * 订单状态
   */
  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#INT32"
  )
  public final Integer status;

  public AddInsureRsp(String insureNO, String lastAssessTime, Integer score, Integer status) {
    this(insureNO, lastAssessTime, score, status, ByteString.EMPTY);
  }

  public AddInsureRsp(String insureNO, String lastAssessTime, Integer score, Integer status, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.insureNO = insureNO;
    this.lastAssessTime = lastAssessTime;
    this.score = score;
    this.status = status;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.insureNO = insureNO;
    builder.lastAssessTime = lastAssessTime;
    builder.score = score;
    builder.status = status;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AddInsureRsp)) return false;
    AddInsureRsp o = (AddInsureRsp) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(insureNO, o.insureNO)
        && Internal.equals(lastAssessTime, o.lastAssessTime)
        && Internal.equals(score, o.score)
        && Internal.equals(status, o.status);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (insureNO != null ? insureNO.hashCode() : 0);
      result = result * 37 + (lastAssessTime != null ? lastAssessTime.hashCode() : 0);
      result = result * 37 + (score != null ? score.hashCode() : 0);
      result = result * 37 + (status != null ? status.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (insureNO != null) builder.append(", insureNO=").append(insureNO);
    if (lastAssessTime != null) builder.append(", lastAssessTime=").append(lastAssessTime);
    if (score != null) builder.append(", score=").append(score);
    if (status != null) builder.append(", status=").append(status);
    return builder.replace(0, 2, "AddInsureRsp{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<AddInsureRsp, Builder> {
    public String insureNO;

    public String lastAssessTime;

    public Integer score;

    public Integer status;

    public Builder() {
    }

    public Builder insureNO(String insureNO) {
      this.insureNO = insureNO;
      return this;
    }

    /**
     * 上次自评时间
     */
    public Builder lastAssessTime(String lastAssessTime) {
      this.lastAssessTime = lastAssessTime;
      return this;
    }

    /**
     * 上次自评分数 -1 即没有自评过 -2有自评，且不需要自评，直接去详情
     */
    public Builder score(Integer score) {
      this.score = score;
      return this;
    }

    /**
     * 订单状态
     */
    public Builder status(Integer status) {
      this.status = status;
      return this;
    }

    @Override
    public AddInsureRsp build() {
      return new AddInsureRsp(insureNO, lastAssessTime, score, status, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_AddInsureRsp extends ProtoAdapter<AddInsureRsp> {
    ProtoAdapter_AddInsureRsp() {
      super(FieldEncoding.LENGTH_DELIMITED, AddInsureRsp.class);
    }

    @Override
    public int encodedSize(AddInsureRsp value) {
      return (value.insureNO != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.insureNO) : 0)
          + (value.lastAssessTime != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.lastAssessTime) : 0)
          + (value.score != null ? ProtoAdapter.INT32.encodedSizeWithTag(3, value.score) : 0)
          + (value.status != null ? ProtoAdapter.INT32.encodedSizeWithTag(4, value.status) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, AddInsureRsp value) throws IOException {
      if (value.insureNO != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.insureNO);
      if (value.lastAssessTime != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.lastAssessTime);
      if (value.score != null) ProtoAdapter.INT32.encodeWithTag(writer, 3, value.score);
      if (value.status != null) ProtoAdapter.INT32.encodeWithTag(writer, 4, value.status);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public AddInsureRsp decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.insureNO(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.lastAssessTime(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.score(ProtoAdapter.INT32.decode(reader)); break;
          case 4: builder.status(ProtoAdapter.INT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public AddInsureRsp redact(AddInsureRsp value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
