// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: AppInterface.proto at 2106:1
package com.yijianyi.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * 复制照护计划
 */
public final class CopyOrderTendReq extends Message<CopyOrderTendReq, CopyOrderTendReq.Builder> {
  public static final ProtoAdapter<CopyOrderTendReq> ADAPTER = new ProtoAdapter_CopyOrderTendReq();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_ORDERTENDID = 0L;

  /**
   * 照护计划id
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long orderTendId;

  public CopyOrderTendReq(Long orderTendId) {
    this(orderTendId, ByteString.EMPTY);
  }

  public CopyOrderTendReq(Long orderTendId, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.orderTendId = orderTendId;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.orderTendId = orderTendId;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof CopyOrderTendReq)) return false;
    CopyOrderTendReq o = (CopyOrderTendReq) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(orderTendId, o.orderTendId);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (orderTendId != null ? orderTendId.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (orderTendId != null) builder.append(", orderTendId=").append(orderTendId);
    return builder.replace(0, 2, "CopyOrderTendReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<CopyOrderTendReq, Builder> {
    public Long orderTendId;

    public Builder() {
    }

    /**
     * 照护计划id
     */
    public Builder orderTendId(Long orderTendId) {
      this.orderTendId = orderTendId;
      return this;
    }

    @Override
    public CopyOrderTendReq build() {
      return new CopyOrderTendReq(orderTendId, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_CopyOrderTendReq extends ProtoAdapter<CopyOrderTendReq> {
    ProtoAdapter_CopyOrderTendReq() {
      super(FieldEncoding.LENGTH_DELIMITED, CopyOrderTendReq.class);
    }

    @Override
    public int encodedSize(CopyOrderTendReq value) {
      return (value.orderTendId != null ? ProtoAdapter.UINT64.encodedSizeWithTag(1, value.orderTendId) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, CopyOrderTendReq value) throws IOException {
      if (value.orderTendId != null) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.orderTendId);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public CopyOrderTendReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.orderTendId(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public CopyOrderTendReq redact(CopyOrderTendReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
