// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: SaasModel.proto at 1341:1
package com.yijianyi.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * 系统异常数据记录
 */
public final class ErrorModel extends Message<ErrorModel, ErrorModel.Builder> {
  public static final ProtoAdapter<ErrorModel> ADAPTER = new ProtoAdapter_ErrorModel();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_ID = 0L;

  public static final Long DEFAULT_USERID = 0L;

  public static final String DEFAULT_USERNAME = "";

  public static final Long DEFAULT_HGID = 0L;

  public static final String DEFAULT_HGNAME = "";

  public static final Integer DEFAULT_CREATETYPE = 0;

  public static final Integer DEFAULT_TERRACETYPE = 0;

  public static final Integer DEFAULT_ERRORTYPE = 0;

  public static final Long DEFAULT_CREATETIME = 0L;

  public static final String DEFAULT_LOGTEXT = "";

  public static final String DEFAULT_URL = "";

  /**
   * id
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long id;

  /**
   * 用户id
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long userId;

  /**
   * 用户昵称
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String userName;

  /**
   * 员工id
   */
  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long hgId;

  /**
   * 员工昵称
   */
  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String hgName;

  /**
   * 异常来源 1-用户app 2-saas 3-企业app 4-用户h5
   */
  @WireField(
      tag = 6,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer createType;

  /**
   * 异常来源平台 1-安卓 2-ios 3-h5
   */
  @WireField(
      tag = 7,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer terraceType;

  /**
   * 异常类型 0-页面错误 1-服务器异常
   */
  @WireField(
      tag = 8,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer errorType;

  /**
   * 创建时间
   */
  @WireField(
      tag = 9,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long createTime;

  /**
   * 页面错误日志
   */
  @WireField(
      tag = 10,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String logText;

  /**
   * 错误页面路径
   */
  @WireField(
      tag = 11,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String url;

  public ErrorModel(Long id, Long userId, String userName, Long hgId, String hgName, Integer createType, Integer terraceType, Integer errorType, Long createTime, String logText, String url) {
    this(id, userId, userName, hgId, hgName, createType, terraceType, errorType, createTime, logText, url, ByteString.EMPTY);
  }

  public ErrorModel(Long id, Long userId, String userName, Long hgId, String hgName, Integer createType, Integer terraceType, Integer errorType, Long createTime, String logText, String url, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.id = id;
    this.userId = userId;
    this.userName = userName;
    this.hgId = hgId;
    this.hgName = hgName;
    this.createType = createType;
    this.terraceType = terraceType;
    this.errorType = errorType;
    this.createTime = createTime;
    this.logText = logText;
    this.url = url;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.id = id;
    builder.userId = userId;
    builder.userName = userName;
    builder.hgId = hgId;
    builder.hgName = hgName;
    builder.createType = createType;
    builder.terraceType = terraceType;
    builder.errorType = errorType;
    builder.createTime = createTime;
    builder.logText = logText;
    builder.url = url;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof ErrorModel)) return false;
    ErrorModel o = (ErrorModel) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(id, o.id)
        && Internal.equals(userId, o.userId)
        && Internal.equals(userName, o.userName)
        && Internal.equals(hgId, o.hgId)
        && Internal.equals(hgName, o.hgName)
        && Internal.equals(createType, o.createType)
        && Internal.equals(terraceType, o.terraceType)
        && Internal.equals(errorType, o.errorType)
        && Internal.equals(createTime, o.createTime)
        && Internal.equals(logText, o.logText)
        && Internal.equals(url, o.url);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (id != null ? id.hashCode() : 0);
      result = result * 37 + (userId != null ? userId.hashCode() : 0);
      result = result * 37 + (userName != null ? userName.hashCode() : 0);
      result = result * 37 + (hgId != null ? hgId.hashCode() : 0);
      result = result * 37 + (hgName != null ? hgName.hashCode() : 0);
      result = result * 37 + (createType != null ? createType.hashCode() : 0);
      result = result * 37 + (terraceType != null ? terraceType.hashCode() : 0);
      result = result * 37 + (errorType != null ? errorType.hashCode() : 0);
      result = result * 37 + (createTime != null ? createTime.hashCode() : 0);
      result = result * 37 + (logText != null ? logText.hashCode() : 0);
      result = result * 37 + (url != null ? url.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (id != null) builder.append(", id=").append(id);
    if (userId != null) builder.append(", userId=").append(userId);
    if (userName != null) builder.append(", userName=").append(userName);
    if (hgId != null) builder.append(", hgId=").append(hgId);
    if (hgName != null) builder.append(", hgName=").append(hgName);
    if (createType != null) builder.append(", createType=").append(createType);
    if (terraceType != null) builder.append(", terraceType=").append(terraceType);
    if (errorType != null) builder.append(", errorType=").append(errorType);
    if (createTime != null) builder.append(", createTime=").append(createTime);
    if (logText != null) builder.append(", logText=").append(logText);
    if (url != null) builder.append(", url=").append(url);
    return builder.replace(0, 2, "ErrorModel{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<ErrorModel, Builder> {
    public Long id;

    public Long userId;

    public String userName;

    public Long hgId;

    public String hgName;

    public Integer createType;

    public Integer terraceType;

    public Integer errorType;

    public Long createTime;

    public String logText;

    public String url;

    public Builder() {
    }

    /**
     * id
     */
    public Builder id(Long id) {
      this.id = id;
      return this;
    }

    /**
     * 用户id
     */
    public Builder userId(Long userId) {
      this.userId = userId;
      return this;
    }

    /**
     * 用户昵称
     */
    public Builder userName(String userName) {
      this.userName = userName;
      return this;
    }

    /**
     * 员工id
     */
    public Builder hgId(Long hgId) {
      this.hgId = hgId;
      return this;
    }

    /**
     * 员工昵称
     */
    public Builder hgName(String hgName) {
      this.hgName = hgName;
      return this;
    }

    /**
     * 异常来源 1-用户app 2-saas 3-企业app 4-用户h5
     */
    public Builder createType(Integer createType) {
      this.createType = createType;
      return this;
    }

    /**
     * 异常来源平台 1-安卓 2-ios 3-h5
     */
    public Builder terraceType(Integer terraceType) {
      this.terraceType = terraceType;
      return this;
    }

    /**
     * 异常类型 0-页面错误 1-服务器异常
     */
    public Builder errorType(Integer errorType) {
      this.errorType = errorType;
      return this;
    }

    /**
     * 创建时间
     */
    public Builder createTime(Long createTime) {
      this.createTime = createTime;
      return this;
    }

    /**
     * 页面错误日志
     */
    public Builder logText(String logText) {
      this.logText = logText;
      return this;
    }

    /**
     * 错误页面路径
     */
    public Builder url(String url) {
      this.url = url;
      return this;
    }

    @Override
    public ErrorModel build() {
      return new ErrorModel(id, userId, userName, hgId, hgName, createType, terraceType, errorType, createTime, logText, url, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_ErrorModel extends ProtoAdapter<ErrorModel> {
    ProtoAdapter_ErrorModel() {
      super(FieldEncoding.LENGTH_DELIMITED, ErrorModel.class);
    }

    @Override
    public int encodedSize(ErrorModel value) {
      return (value.id != null ? ProtoAdapter.UINT64.encodedSizeWithTag(1, value.id) : 0)
          + (value.userId != null ? ProtoAdapter.UINT64.encodedSizeWithTag(2, value.userId) : 0)
          + (value.userName != null ? ProtoAdapter.STRING.encodedSizeWithTag(3, value.userName) : 0)
          + (value.hgId != null ? ProtoAdapter.UINT64.encodedSizeWithTag(4, value.hgId) : 0)
          + (value.hgName != null ? ProtoAdapter.STRING.encodedSizeWithTag(5, value.hgName) : 0)
          + (value.createType != null ? ProtoAdapter.UINT32.encodedSizeWithTag(6, value.createType) : 0)
          + (value.terraceType != null ? ProtoAdapter.UINT32.encodedSizeWithTag(7, value.terraceType) : 0)
          + (value.errorType != null ? ProtoAdapter.UINT32.encodedSizeWithTag(8, value.errorType) : 0)
          + (value.createTime != null ? ProtoAdapter.UINT64.encodedSizeWithTag(9, value.createTime) : 0)
          + (value.logText != null ? ProtoAdapter.STRING.encodedSizeWithTag(10, value.logText) : 0)
          + (value.url != null ? ProtoAdapter.STRING.encodedSizeWithTag(11, value.url) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, ErrorModel value) throws IOException {
      if (value.id != null) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.id);
      if (value.userId != null) ProtoAdapter.UINT64.encodeWithTag(writer, 2, value.userId);
      if (value.userName != null) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.userName);
      if (value.hgId != null) ProtoAdapter.UINT64.encodeWithTag(writer, 4, value.hgId);
      if (value.hgName != null) ProtoAdapter.STRING.encodeWithTag(writer, 5, value.hgName);
      if (value.createType != null) ProtoAdapter.UINT32.encodeWithTag(writer, 6, value.createType);
      if (value.terraceType != null) ProtoAdapter.UINT32.encodeWithTag(writer, 7, value.terraceType);
      if (value.errorType != null) ProtoAdapter.UINT32.encodeWithTag(writer, 8, value.errorType);
      if (value.createTime != null) ProtoAdapter.UINT64.encodeWithTag(writer, 9, value.createTime);
      if (value.logText != null) ProtoAdapter.STRING.encodeWithTag(writer, 10, value.logText);
      if (value.url != null) ProtoAdapter.STRING.encodeWithTag(writer, 11, value.url);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public ErrorModel decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.id(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.userId(ProtoAdapter.UINT64.decode(reader)); break;
          case 3: builder.userName(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.hgId(ProtoAdapter.UINT64.decode(reader)); break;
          case 5: builder.hgName(ProtoAdapter.STRING.decode(reader)); break;
          case 6: builder.createType(ProtoAdapter.UINT32.decode(reader)); break;
          case 7: builder.terraceType(ProtoAdapter.UINT32.decode(reader)); break;
          case 8: builder.errorType(ProtoAdapter.UINT32.decode(reader)); break;
          case 9: builder.createTime(ProtoAdapter.UINT64.decode(reader)); break;
          case 10: builder.logText(ProtoAdapter.STRING.decode(reader)); break;
          case 11: builder.url(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public ErrorModel redact(ErrorModel value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
