// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: AppInterface.proto at 1076:1
package com.yijianyi.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

/**
 * 获取我的护士、护工列表
 */
public final class GetHgRsp extends Message<GetHgRsp, GetHgRsp.Builder> {
  public static final ProtoAdapter<GetHgRsp> ADAPTER = new ProtoAdapter_GetHgRsp();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_COUNT = 0;

  /**
   * 信息
   */
  @WireField(
      tag = 1,
      adapter = "com.yijianyi.protocol.HgVO#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<HgVO> hgVO;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer count;

  public GetHgRsp(List<HgVO> hgVO, Integer count) {
    this(hgVO, count, ByteString.EMPTY);
  }

  public GetHgRsp(List<HgVO> hgVO, Integer count, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.hgVO = Internal.immutableCopyOf("hgVO", hgVO);
    this.count = count;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.hgVO = Internal.copyOf("hgVO", hgVO);
    builder.count = count;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetHgRsp)) return false;
    GetHgRsp o = (GetHgRsp) other;
    return unknownFields().equals(o.unknownFields())
        && hgVO.equals(o.hgVO)
        && Internal.equals(count, o.count);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + hgVO.hashCode();
      result = result * 37 + (count != null ? count.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!hgVO.isEmpty()) builder.append(", hgVO=").append(hgVO);
    if (count != null) builder.append(", count=").append(count);
    return builder.replace(0, 2, "GetHgRsp{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetHgRsp, Builder> {
    public List<HgVO> hgVO;

    public Integer count;

    public Builder() {
      hgVO = Internal.newMutableList();
    }

    /**
     * 信息
     */
    public Builder hgVO(List<HgVO> hgVO) {
      Internal.checkElementsNotNull(hgVO);
      this.hgVO = hgVO;
      return this;
    }

    public Builder count(Integer count) {
      this.count = count;
      return this;
    }

    @Override
    public GetHgRsp build() {
      return new GetHgRsp(hgVO, count, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetHgRsp extends ProtoAdapter<GetHgRsp> {
    ProtoAdapter_GetHgRsp() {
      super(FieldEncoding.LENGTH_DELIMITED, GetHgRsp.class);
    }

    @Override
    public int encodedSize(GetHgRsp value) {
      return HgVO.ADAPTER.asRepeated().encodedSizeWithTag(1, value.hgVO)
          + (value.count != null ? ProtoAdapter.UINT32.encodedSizeWithTag(2, value.count) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetHgRsp value) throws IOException {
      HgVO.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.hgVO);
      if (value.count != null) ProtoAdapter.UINT32.encodeWithTag(writer, 2, value.count);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetHgRsp decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.hgVO.add(HgVO.ADAPTER.decode(reader)); break;
          case 2: builder.count(ProtoAdapter.UINT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetHgRsp redact(GetHgRsp value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.hgVO, HgVO.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
