// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: AppInterface.proto at 1271:1
package com.yijianyi.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * 长护险详情
 */
public final class GetInsureDetailReq extends Message<GetInsureDetailReq, GetInsureDetailReq.Builder> {
  public static final ProtoAdapter<GetInsureDetailReq> ADAPTER = new ProtoAdapter_GetInsureDetailReq();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_INSUREID = "";

  /**
   * 申请单号
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String insureId;

  public GetInsureDetailReq(String insureId) {
    this(insureId, ByteString.EMPTY);
  }

  public GetInsureDetailReq(String insureId, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.insureId = insureId;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.insureId = insureId;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetInsureDetailReq)) return false;
    GetInsureDetailReq o = (GetInsureDetailReq) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(insureId, o.insureId);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (insureId != null ? insureId.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (insureId != null) builder.append(", insureId=").append(insureId);
    return builder.replace(0, 2, "GetInsureDetailReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetInsureDetailReq, Builder> {
    public String insureId;

    public Builder() {
    }

    /**
     * 申请单号
     */
    public Builder insureId(String insureId) {
      this.insureId = insureId;
      return this;
    }

    @Override
    public GetInsureDetailReq build() {
      return new GetInsureDetailReq(insureId, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetInsureDetailReq extends ProtoAdapter<GetInsureDetailReq> {
    ProtoAdapter_GetInsureDetailReq() {
      super(FieldEncoding.LENGTH_DELIMITED, GetInsureDetailReq.class);
    }

    @Override
    public int encodedSize(GetInsureDetailReq value) {
      return (value.insureId != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.insureId) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetInsureDetailReq value) throws IOException {
      if (value.insureId != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.insureId);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetInsureDetailReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.insureId(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetInsureDetailReq redact(GetInsureDetailReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
