// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: AppInterface.proto at 1472:1
package com.yijianyi.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import okio.ByteString;

public final class GetInsurePriceListRsp extends Message<GetInsurePriceListRsp, GetInsurePriceListRsp.Builder> {
  public static final ProtoAdapter<GetInsurePriceListRsp> ADAPTER = new ProtoAdapter_GetInsurePriceListRsp();

  private static final long serialVersionUID = 0L;

  /**
   * 服务列表
   */
  @WireField(
      tag = 1,
      adapter = "com.yijianyi.protocol.InsurePriceVO#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<InsurePriceVO> priceList;

  public GetInsurePriceListRsp(List<InsurePriceVO> priceList) {
    this(priceList, ByteString.EMPTY);
  }

  public GetInsurePriceListRsp(List<InsurePriceVO> priceList, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.priceList = Internal.immutableCopyOf("priceList", priceList);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.priceList = Internal.copyOf("priceList", priceList);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetInsurePriceListRsp)) return false;
    GetInsurePriceListRsp o = (GetInsurePriceListRsp) other;
    return unknownFields().equals(o.unknownFields())
        && priceList.equals(o.priceList);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + priceList.hashCode();
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!priceList.isEmpty()) builder.append(", priceList=").append(priceList);
    return builder.replace(0, 2, "GetInsurePriceListRsp{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetInsurePriceListRsp, Builder> {
    public List<InsurePriceVO> priceList;

    public Builder() {
      priceList = Internal.newMutableList();
    }

    /**
     * 服务列表
     */
    public Builder priceList(List<InsurePriceVO> priceList) {
      Internal.checkElementsNotNull(priceList);
      this.priceList = priceList;
      return this;
    }

    @Override
    public GetInsurePriceListRsp build() {
      return new GetInsurePriceListRsp(priceList, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetInsurePriceListRsp extends ProtoAdapter<GetInsurePriceListRsp> {
    ProtoAdapter_GetInsurePriceListRsp() {
      super(FieldEncoding.LENGTH_DELIMITED, GetInsurePriceListRsp.class);
    }

    @Override
    public int encodedSize(GetInsurePriceListRsp value) {
      return InsurePriceVO.ADAPTER.asRepeated().encodedSizeWithTag(1, value.priceList)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetInsurePriceListRsp value) throws IOException {
      InsurePriceVO.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.priceList);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetInsurePriceListRsp decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.priceList.add(InsurePriceVO.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetInsurePriceListRsp redact(GetInsurePriceListRsp value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.priceList, InsurePriceVO.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
