// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: AppInterface.proto at 302:1
package com.yijianyi.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * 获取身份证号码的请求协议
 */
public final class GetIDCardNoReq extends Message<GetIDCardNoReq, GetIDCardNoReq.Builder> {
  public static final ProtoAdapter<GetIDCardNoReq> ADAPTER = new ProtoAdapter_GetIDCardNoReq();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_IMGID = "";

  /**
   * 身份证照片在图片服务器上面的id
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String imgId;

  public GetIDCardNoReq(String imgId) {
    this(imgId, ByteString.EMPTY);
  }

  public GetIDCardNoReq(String imgId, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.imgId = imgId;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.imgId = imgId;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetIDCardNoReq)) return false;
    GetIDCardNoReq o = (GetIDCardNoReq) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(imgId, o.imgId);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (imgId != null ? imgId.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (imgId != null) builder.append(", imgId=").append(imgId);
    return builder.replace(0, 2, "GetIDCardNoReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetIDCardNoReq, Builder> {
    public String imgId;

    public Builder() {
    }

    /**
     * 身份证照片在图片服务器上面的id
     */
    public Builder imgId(String imgId) {
      this.imgId = imgId;
      return this;
    }

    @Override
    public GetIDCardNoReq build() {
      return new GetIDCardNoReq(imgId, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetIDCardNoReq extends ProtoAdapter<GetIDCardNoReq> {
    ProtoAdapter_GetIDCardNoReq() {
      super(FieldEncoding.LENGTH_DELIMITED, GetIDCardNoReq.class);
    }

    @Override
    public int encodedSize(GetIDCardNoReq value) {
      return (value.imgId != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.imgId) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetIDCardNoReq value) throws IOException {
      if (value.imgId != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.imgId);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetIDCardNoReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.imgId(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetIDCardNoReq redact(GetIDCardNoReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
