// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: AppInterface.proto at 1539:1
package com.yijianyi.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * 长护险订单被陪护人信息
 */
public final class GetKinsInsureReq extends Message<GetKinsInsureReq, GetKinsInsureReq.Builder> {
  public static final ProtoAdapter<GetKinsInsureReq> ADAPTER = new ProtoAdapter_GetKinsInsureReq();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_ORDERID = "";

  public static final String DEFAULT_HGNONAME = "";

  /**
   * 长护险申请单id
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String orderId;

  /**
   * 工号姓名
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String hgnoName;

  public GetKinsInsureReq(String orderId, String hgnoName) {
    this(orderId, hgnoName, ByteString.EMPTY);
  }

  public GetKinsInsureReq(String orderId, String hgnoName, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.orderId = orderId;
    this.hgnoName = hgnoName;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.orderId = orderId;
    builder.hgnoName = hgnoName;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetKinsInsureReq)) return false;
    GetKinsInsureReq o = (GetKinsInsureReq) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(orderId, o.orderId)
        && Internal.equals(hgnoName, o.hgnoName);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (orderId != null ? orderId.hashCode() : 0);
      result = result * 37 + (hgnoName != null ? hgnoName.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (orderId != null) builder.append(", orderId=").append(orderId);
    if (hgnoName != null) builder.append(", hgnoName=").append(hgnoName);
    return builder.replace(0, 2, "GetKinsInsureReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetKinsInsureReq, Builder> {
    public String orderId;

    public String hgnoName;

    public Builder() {
    }

    /**
     * 长护险申请单id
     */
    public Builder orderId(String orderId) {
      this.orderId = orderId;
      return this;
    }

    /**
     * 工号姓名
     */
    public Builder hgnoName(String hgnoName) {
      this.hgnoName = hgnoName;
      return this;
    }

    @Override
    public GetKinsInsureReq build() {
      return new GetKinsInsureReq(orderId, hgnoName, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetKinsInsureReq extends ProtoAdapter<GetKinsInsureReq> {
    ProtoAdapter_GetKinsInsureReq() {
      super(FieldEncoding.LENGTH_DELIMITED, GetKinsInsureReq.class);
    }

    @Override
    public int encodedSize(GetKinsInsureReq value) {
      return (value.orderId != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.orderId) : 0)
          + (value.hgnoName != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.hgnoName) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetKinsInsureReq value) throws IOException {
      if (value.orderId != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.orderId);
      if (value.hgnoName != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.hgnoName);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetKinsInsureReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.orderId(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.hgnoName(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetKinsInsureReq redact(GetKinsInsureReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
