// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: AppInterface.proto at 1047:1
package com.yijianyi.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * 获取被陪护人信息
 */
public final class GetKinsfolkReq extends Message<GetKinsfolkReq, GetKinsfolkReq.Builder> {
  public static final ProtoAdapter<GetKinsfolkReq> ADAPTER = new ProtoAdapter_GetKinsfolkReq();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_KINSID = 0L;

  public static final String DEFAULT_IDCARDNO = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long kinsId;

  /**
   * 身份证
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String idCardNo;

  public GetKinsfolkReq(Long kinsId, String idCardNo) {
    this(kinsId, idCardNo, ByteString.EMPTY);
  }

  public GetKinsfolkReq(Long kinsId, String idCardNo, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.kinsId = kinsId;
    this.idCardNo = idCardNo;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.kinsId = kinsId;
    builder.idCardNo = idCardNo;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof GetKinsfolkReq)) return false;
    GetKinsfolkReq o = (GetKinsfolkReq) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(kinsId, o.kinsId)
        && Internal.equals(idCardNo, o.idCardNo);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (kinsId != null ? kinsId.hashCode() : 0);
      result = result * 37 + (idCardNo != null ? idCardNo.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (kinsId != null) builder.append(", kinsId=").append(kinsId);
    if (idCardNo != null) builder.append(", idCardNo=").append(idCardNo);
    return builder.replace(0, 2, "GetKinsfolkReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<GetKinsfolkReq, Builder> {
    public Long kinsId;

    public String idCardNo;

    public Builder() {
    }

    public Builder kinsId(Long kinsId) {
      this.kinsId = kinsId;
      return this;
    }

    /**
     * 身份证
     */
    public Builder idCardNo(String idCardNo) {
      this.idCardNo = idCardNo;
      return this;
    }

    @Override
    public GetKinsfolkReq build() {
      return new GetKinsfolkReq(kinsId, idCardNo, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_GetKinsfolkReq extends ProtoAdapter<GetKinsfolkReq> {
    ProtoAdapter_GetKinsfolkReq() {
      super(FieldEncoding.LENGTH_DELIMITED, GetKinsfolkReq.class);
    }

    @Override
    public int encodedSize(GetKinsfolkReq value) {
      return (value.kinsId != null ? ProtoAdapter.UINT64.encodedSizeWithTag(1, value.kinsId) : 0)
          + (value.idCardNo != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.idCardNo) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, GetKinsfolkReq value) throws IOException {
      if (value.kinsId != null) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.kinsId);
      if (value.idCardNo != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.idCardNo);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public GetKinsfolkReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.kinsId(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.idCardNo(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public GetKinsfolkReq redact(GetKinsfolkReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
