// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: AssessModel.proto at 121:1
package com.yijianyi.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * 老年人能力评估-感知觉与沟通
 */
public final class InsureAssessAbilityComm extends Message<InsureAssessAbilityComm, InsureAssessAbilityComm.Builder> {
  public static final ProtoAdapter<InsureAssessAbilityComm> ADAPTER = new ProtoAdapter_InsureAssessAbilityComm();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_ID = 0L;

  public static final Long DEFAULT_RESULTID = 0L;

  public static final Integer DEFAULT_SCORE = 0;

  public static final Integer DEFAULT_LEVEL = 0;

  public static final Integer DEFAULT_MENTALITY = 0;

  public static final Integer DEFAULT_VISION = 0;

  public static final Integer DEFAULT_HEARING = 0;

  public static final Integer DEFAULT_COMMUNICATION = 0;

  public static final Long DEFAULT_CREATETIME = 0L;

  public static final Long DEFAULT_CREATESTAFFID = 0L;

  public static final String DEFAULT_CREATESTAFFNAME = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long id;

  /**
   * 报告id
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long resultId;

  /**
   * 评估分数
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer score;

  /**
   * 感知觉与沟通分级（根据每个选项得出） 0-能力完好 1-轻度受损 2-中度受损 3-重度受损
   */
  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer level;

  /**
   * 意识水平
   */
  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer mentality;

  /**
   * 视力
   */
  @WireField(
      tag = 6,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer vision;

  /**
   * 听力
   */
  @WireField(
      tag = 7,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer hearing;

  /**
   * 沟通交流
   */
  @WireField(
      tag = 8,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer communication;

  /**
   * 本次评估时间
   */
  @WireField(
      tag = 9,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long createTime;

  /**
   * 操作员工ID
   */
  @WireField(
      tag = 10,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long createStaffId;

  /**
   * 评估人员
   */
  @WireField(
      tag = 11,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String createStaffName;

  public InsureAssessAbilityComm(Long id, Long resultId, Integer score, Integer level, Integer mentality, Integer vision, Integer hearing, Integer communication, Long createTime, Long createStaffId, String createStaffName) {
    this(id, resultId, score, level, mentality, vision, hearing, communication, createTime, createStaffId, createStaffName, ByteString.EMPTY);
  }

  public InsureAssessAbilityComm(Long id, Long resultId, Integer score, Integer level, Integer mentality, Integer vision, Integer hearing, Integer communication, Long createTime, Long createStaffId, String createStaffName, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.id = id;
    this.resultId = resultId;
    this.score = score;
    this.level = level;
    this.mentality = mentality;
    this.vision = vision;
    this.hearing = hearing;
    this.communication = communication;
    this.createTime = createTime;
    this.createStaffId = createStaffId;
    this.createStaffName = createStaffName;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.id = id;
    builder.resultId = resultId;
    builder.score = score;
    builder.level = level;
    builder.mentality = mentality;
    builder.vision = vision;
    builder.hearing = hearing;
    builder.communication = communication;
    builder.createTime = createTime;
    builder.createStaffId = createStaffId;
    builder.createStaffName = createStaffName;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof InsureAssessAbilityComm)) return false;
    InsureAssessAbilityComm o = (InsureAssessAbilityComm) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(id, o.id)
        && Internal.equals(resultId, o.resultId)
        && Internal.equals(score, o.score)
        && Internal.equals(level, o.level)
        && Internal.equals(mentality, o.mentality)
        && Internal.equals(vision, o.vision)
        && Internal.equals(hearing, o.hearing)
        && Internal.equals(communication, o.communication)
        && Internal.equals(createTime, o.createTime)
        && Internal.equals(createStaffId, o.createStaffId)
        && Internal.equals(createStaffName, o.createStaffName);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (id != null ? id.hashCode() : 0);
      result = result * 37 + (resultId != null ? resultId.hashCode() : 0);
      result = result * 37 + (score != null ? score.hashCode() : 0);
      result = result * 37 + (level != null ? level.hashCode() : 0);
      result = result * 37 + (mentality != null ? mentality.hashCode() : 0);
      result = result * 37 + (vision != null ? vision.hashCode() : 0);
      result = result * 37 + (hearing != null ? hearing.hashCode() : 0);
      result = result * 37 + (communication != null ? communication.hashCode() : 0);
      result = result * 37 + (createTime != null ? createTime.hashCode() : 0);
      result = result * 37 + (createStaffId != null ? createStaffId.hashCode() : 0);
      result = result * 37 + (createStaffName != null ? createStaffName.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (id != null) builder.append(", id=").append(id);
    if (resultId != null) builder.append(", resultId=").append(resultId);
    if (score != null) builder.append(", score=").append(score);
    if (level != null) builder.append(", level=").append(level);
    if (mentality != null) builder.append(", mentality=").append(mentality);
    if (vision != null) builder.append(", vision=").append(vision);
    if (hearing != null) builder.append(", hearing=").append(hearing);
    if (communication != null) builder.append(", communication=").append(communication);
    if (createTime != null) builder.append(", createTime=").append(createTime);
    if (createStaffId != null) builder.append(", createStaffId=").append(createStaffId);
    if (createStaffName != null) builder.append(", createStaffName=").append(createStaffName);
    return builder.replace(0, 2, "InsureAssessAbilityComm{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<InsureAssessAbilityComm, Builder> {
    public Long id;

    public Long resultId;

    public Integer score;

    public Integer level;

    public Integer mentality;

    public Integer vision;

    public Integer hearing;

    public Integer communication;

    public Long createTime;

    public Long createStaffId;

    public String createStaffName;

    public Builder() {
    }

    public Builder id(Long id) {
      this.id = id;
      return this;
    }

    /**
     * 报告id
     */
    public Builder resultId(Long resultId) {
      this.resultId = resultId;
      return this;
    }

    /**
     * 评估分数
     */
    public Builder score(Integer score) {
      this.score = score;
      return this;
    }

    /**
     * 感知觉与沟通分级（根据每个选项得出） 0-能力完好 1-轻度受损 2-中度受损 3-重度受损
     */
    public Builder level(Integer level) {
      this.level = level;
      return this;
    }

    /**
     * 意识水平
     */
    public Builder mentality(Integer mentality) {
      this.mentality = mentality;
      return this;
    }

    /**
     * 视力
     */
    public Builder vision(Integer vision) {
      this.vision = vision;
      return this;
    }

    /**
     * 听力
     */
    public Builder hearing(Integer hearing) {
      this.hearing = hearing;
      return this;
    }

    /**
     * 沟通交流
     */
    public Builder communication(Integer communication) {
      this.communication = communication;
      return this;
    }

    /**
     * 本次评估时间
     */
    public Builder createTime(Long createTime) {
      this.createTime = createTime;
      return this;
    }

    /**
     * 操作员工ID
     */
    public Builder createStaffId(Long createStaffId) {
      this.createStaffId = createStaffId;
      return this;
    }

    /**
     * 评估人员
     */
    public Builder createStaffName(String createStaffName) {
      this.createStaffName = createStaffName;
      return this;
    }

    @Override
    public InsureAssessAbilityComm build() {
      return new InsureAssessAbilityComm(id, resultId, score, level, mentality, vision, hearing, communication, createTime, createStaffId, createStaffName, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_InsureAssessAbilityComm extends ProtoAdapter<InsureAssessAbilityComm> {
    ProtoAdapter_InsureAssessAbilityComm() {
      super(FieldEncoding.LENGTH_DELIMITED, InsureAssessAbilityComm.class);
    }

    @Override
    public int encodedSize(InsureAssessAbilityComm value) {
      return (value.id != null ? ProtoAdapter.UINT64.encodedSizeWithTag(1, value.id) : 0)
          + (value.resultId != null ? ProtoAdapter.UINT64.encodedSizeWithTag(2, value.resultId) : 0)
          + (value.score != null ? ProtoAdapter.UINT32.encodedSizeWithTag(3, value.score) : 0)
          + (value.level != null ? ProtoAdapter.UINT32.encodedSizeWithTag(4, value.level) : 0)
          + (value.mentality != null ? ProtoAdapter.UINT32.encodedSizeWithTag(5, value.mentality) : 0)
          + (value.vision != null ? ProtoAdapter.UINT32.encodedSizeWithTag(6, value.vision) : 0)
          + (value.hearing != null ? ProtoAdapter.UINT32.encodedSizeWithTag(7, value.hearing) : 0)
          + (value.communication != null ? ProtoAdapter.UINT32.encodedSizeWithTag(8, value.communication) : 0)
          + (value.createTime != null ? ProtoAdapter.UINT64.encodedSizeWithTag(9, value.createTime) : 0)
          + (value.createStaffId != null ? ProtoAdapter.UINT64.encodedSizeWithTag(10, value.createStaffId) : 0)
          + (value.createStaffName != null ? ProtoAdapter.STRING.encodedSizeWithTag(11, value.createStaffName) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, InsureAssessAbilityComm value) throws IOException {
      if (value.id != null) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.id);
      if (value.resultId != null) ProtoAdapter.UINT64.encodeWithTag(writer, 2, value.resultId);
      if (value.score != null) ProtoAdapter.UINT32.encodeWithTag(writer, 3, value.score);
      if (value.level != null) ProtoAdapter.UINT32.encodeWithTag(writer, 4, value.level);
      if (value.mentality != null) ProtoAdapter.UINT32.encodeWithTag(writer, 5, value.mentality);
      if (value.vision != null) ProtoAdapter.UINT32.encodeWithTag(writer, 6, value.vision);
      if (value.hearing != null) ProtoAdapter.UINT32.encodeWithTag(writer, 7, value.hearing);
      if (value.communication != null) ProtoAdapter.UINT32.encodeWithTag(writer, 8, value.communication);
      if (value.createTime != null) ProtoAdapter.UINT64.encodeWithTag(writer, 9, value.createTime);
      if (value.createStaffId != null) ProtoAdapter.UINT64.encodeWithTag(writer, 10, value.createStaffId);
      if (value.createStaffName != null) ProtoAdapter.STRING.encodeWithTag(writer, 11, value.createStaffName);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public InsureAssessAbilityComm decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.id(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.resultId(ProtoAdapter.UINT64.decode(reader)); break;
          case 3: builder.score(ProtoAdapter.UINT32.decode(reader)); break;
          case 4: builder.level(ProtoAdapter.UINT32.decode(reader)); break;
          case 5: builder.mentality(ProtoAdapter.UINT32.decode(reader)); break;
          case 6: builder.vision(ProtoAdapter.UINT32.decode(reader)); break;
          case 7: builder.hearing(ProtoAdapter.UINT32.decode(reader)); break;
          case 8: builder.communication(ProtoAdapter.UINT32.decode(reader)); break;
          case 9: builder.createTime(ProtoAdapter.UINT64.decode(reader)); break;
          case 10: builder.createStaffId(ProtoAdapter.UINT64.decode(reader)); break;
          case 11: builder.createStaffName(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public InsureAssessAbilityComm redact(InsureAssessAbilityComm value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
