// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: SaasModel.proto at 1380:1
package com.yijianyi.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class InsurePriceVO extends Message<InsurePriceVO, InsurePriceVO.Builder> {
  public static final ProtoAdapter<InsurePriceVO> ADAPTER = new ProtoAdapter_InsurePriceVO();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_PRICEID = 0L;

  public static final String DEFAULT_SERVICEITEM = "";

  public static final String DEFAULT_SERVICEINTRO = "";

  public static final String DEFAULT_PRICEDESC = "";

  public static final Integer DEFAULT_SERVICETYPE = 0;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long priceId;

  /**
   * 服务项目
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String serviceItem;

  /**
   * 服务介绍
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String serviceIntro;

  /**
   * 价格
   */
  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String priceDesc;

  /**
   * 服务类型（长护险陪护服务-180 长护险带教服务-181 长护险自照服务-182）
   */
  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer serviceType;

  public InsurePriceVO(Long priceId, String serviceItem, String serviceIntro, String priceDesc, Integer serviceType) {
    this(priceId, serviceItem, serviceIntro, priceDesc, serviceType, ByteString.EMPTY);
  }

  public InsurePriceVO(Long priceId, String serviceItem, String serviceIntro, String priceDesc, Integer serviceType, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.priceId = priceId;
    this.serviceItem = serviceItem;
    this.serviceIntro = serviceIntro;
    this.priceDesc = priceDesc;
    this.serviceType = serviceType;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.priceId = priceId;
    builder.serviceItem = serviceItem;
    builder.serviceIntro = serviceIntro;
    builder.priceDesc = priceDesc;
    builder.serviceType = serviceType;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof InsurePriceVO)) return false;
    InsurePriceVO o = (InsurePriceVO) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(priceId, o.priceId)
        && Internal.equals(serviceItem, o.serviceItem)
        && Internal.equals(serviceIntro, o.serviceIntro)
        && Internal.equals(priceDesc, o.priceDesc)
        && Internal.equals(serviceType, o.serviceType);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (priceId != null ? priceId.hashCode() : 0);
      result = result * 37 + (serviceItem != null ? serviceItem.hashCode() : 0);
      result = result * 37 + (serviceIntro != null ? serviceIntro.hashCode() : 0);
      result = result * 37 + (priceDesc != null ? priceDesc.hashCode() : 0);
      result = result * 37 + (serviceType != null ? serviceType.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (priceId != null) builder.append(", priceId=").append(priceId);
    if (serviceItem != null) builder.append(", serviceItem=").append(serviceItem);
    if (serviceIntro != null) builder.append(", serviceIntro=").append(serviceIntro);
    if (priceDesc != null) builder.append(", priceDesc=").append(priceDesc);
    if (serviceType != null) builder.append(", serviceType=").append(serviceType);
    return builder.replace(0, 2, "InsurePriceVO{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<InsurePriceVO, Builder> {
    public Long priceId;

    public String serviceItem;

    public String serviceIntro;

    public String priceDesc;

    public Integer serviceType;

    public Builder() {
    }

    public Builder priceId(Long priceId) {
      this.priceId = priceId;
      return this;
    }

    /**
     * 服务项目
     */
    public Builder serviceItem(String serviceItem) {
      this.serviceItem = serviceItem;
      return this;
    }

    /**
     * 服务介绍
     */
    public Builder serviceIntro(String serviceIntro) {
      this.serviceIntro = serviceIntro;
      return this;
    }

    /**
     * 价格
     */
    public Builder priceDesc(String priceDesc) {
      this.priceDesc = priceDesc;
      return this;
    }

    /**
     * 服务类型（长护险陪护服务-180 长护险带教服务-181 长护险自照服务-182）
     */
    public Builder serviceType(Integer serviceType) {
      this.serviceType = serviceType;
      return this;
    }

    @Override
    public InsurePriceVO build() {
      return new InsurePriceVO(priceId, serviceItem, serviceIntro, priceDesc, serviceType, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_InsurePriceVO extends ProtoAdapter<InsurePriceVO> {
    ProtoAdapter_InsurePriceVO() {
      super(FieldEncoding.LENGTH_DELIMITED, InsurePriceVO.class);
    }

    @Override
    public int encodedSize(InsurePriceVO value) {
      return (value.priceId != null ? ProtoAdapter.UINT64.encodedSizeWithTag(1, value.priceId) : 0)
          + (value.serviceItem != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.serviceItem) : 0)
          + (value.serviceIntro != null ? ProtoAdapter.STRING.encodedSizeWithTag(3, value.serviceIntro) : 0)
          + (value.priceDesc != null ? ProtoAdapter.STRING.encodedSizeWithTag(4, value.priceDesc) : 0)
          + (value.serviceType != null ? ProtoAdapter.UINT32.encodedSizeWithTag(5, value.serviceType) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, InsurePriceVO value) throws IOException {
      if (value.priceId != null) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.priceId);
      if (value.serviceItem != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.serviceItem);
      if (value.serviceIntro != null) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.serviceIntro);
      if (value.priceDesc != null) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.priceDesc);
      if (value.serviceType != null) ProtoAdapter.UINT32.encodeWithTag(writer, 5, value.serviceType);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public InsurePriceVO decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.priceId(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.serviceItem(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.serviceIntro(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.priceDesc(ProtoAdapter.STRING.decode(reader)); break;
          case 5: builder.serviceType(ProtoAdapter.UINT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public InsurePriceVO redact(InsurePriceVO value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
