// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: SaasModel.proto at 609:1
package com.yijianyi.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * 医保类型
 */
public final class MedicareType extends Message<MedicareType, MedicareType.Builder> {
  public static final ProtoAdapter<MedicareType> ADAPTER = new ProtoAdapter_MedicareType();

  private static final long serialVersionUID = 0L;

  public static final Integer DEFAULT_ID = 0;

  public static final String DEFAULT_MEDICARE = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer id;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String medicare;

  public MedicareType(Integer id, String medicare) {
    this(id, medicare, ByteString.EMPTY);
  }

  public MedicareType(Integer id, String medicare, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.id = id;
    this.medicare = medicare;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.id = id;
    builder.medicare = medicare;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof MedicareType)) return false;
    MedicareType o = (MedicareType) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(id, o.id)
        && Internal.equals(medicare, o.medicare);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (id != null ? id.hashCode() : 0);
      result = result * 37 + (medicare != null ? medicare.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (id != null) builder.append(", id=").append(id);
    if (medicare != null) builder.append(", medicare=").append(medicare);
    return builder.replace(0, 2, "MedicareType{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<MedicareType, Builder> {
    public Integer id;

    public String medicare;

    public Builder() {
    }

    public Builder id(Integer id) {
      this.id = id;
      return this;
    }

    public Builder medicare(String medicare) {
      this.medicare = medicare;
      return this;
    }

    @Override
    public MedicareType build() {
      return new MedicareType(id, medicare, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_MedicareType extends ProtoAdapter<MedicareType> {
    ProtoAdapter_MedicareType() {
      super(FieldEncoding.LENGTH_DELIMITED, MedicareType.class);
    }

    @Override
    public int encodedSize(MedicareType value) {
      return (value.id != null ? ProtoAdapter.UINT32.encodedSizeWithTag(1, value.id) : 0)
          + (value.medicare != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.medicare) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, MedicareType value) throws IOException {
      if (value.id != null) ProtoAdapter.UINT32.encodeWithTag(writer, 1, value.id);
      if (value.medicare != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.medicare);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public MedicareType decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.id(ProtoAdapter.UINT32.decode(reader)); break;
          case 2: builder.medicare(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public MedicareType redact(MedicareType value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
