// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: AppInterface.proto at 1203:1
package com.yijianyi.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class OrgNORecognizeRsp extends Message<OrgNORecognizeRsp, OrgNORecognizeRsp.Builder> {
  public static final ProtoAdapter<OrgNORecognizeRsp> ADAPTER = new ProtoAdapter_OrgNORecognizeRsp();

  private static final long serialVersionUID = 0L;

  /**
   * 入院数据
   */
  @WireField(
      tag = 1,
      adapter = "com.yijianyi.protocol.HospitalBra#ADAPTER"
  )
  public final HospitalBra hospitalBra;

  public OrgNORecognizeRsp(HospitalBra hospitalBra) {
    this(hospitalBra, ByteString.EMPTY);
  }

  public OrgNORecognizeRsp(HospitalBra hospitalBra, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.hospitalBra = hospitalBra;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.hospitalBra = hospitalBra;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof OrgNORecognizeRsp)) return false;
    OrgNORecognizeRsp o = (OrgNORecognizeRsp) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(hospitalBra, o.hospitalBra);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (hospitalBra != null ? hospitalBra.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (hospitalBra != null) builder.append(", hospitalBra=").append(hospitalBra);
    return builder.replace(0, 2, "OrgNORecognizeRsp{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<OrgNORecognizeRsp, Builder> {
    public HospitalBra hospitalBra;

    public Builder() {
    }

    /**
     * 入院数据
     */
    public Builder hospitalBra(HospitalBra hospitalBra) {
      this.hospitalBra = hospitalBra;
      return this;
    }

    @Override
    public OrgNORecognizeRsp build() {
      return new OrgNORecognizeRsp(hospitalBra, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_OrgNORecognizeRsp extends ProtoAdapter<OrgNORecognizeRsp> {
    ProtoAdapter_OrgNORecognizeRsp() {
      super(FieldEncoding.LENGTH_DELIMITED, OrgNORecognizeRsp.class);
    }

    @Override
    public int encodedSize(OrgNORecognizeRsp value) {
      return (value.hospitalBra != null ? HospitalBra.ADAPTER.encodedSizeWithTag(1, value.hospitalBra) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, OrgNORecognizeRsp value) throws IOException {
      if (value.hospitalBra != null) HospitalBra.ADAPTER.encodeWithTag(writer, 1, value.hospitalBra);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public OrgNORecognizeRsp decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.hospitalBra(HospitalBra.ADAPTER.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public OrgNORecognizeRsp redact(OrgNORecognizeRsp value) {
      Builder builder = value.newBuilder();
      if (builder.hospitalBra != null) builder.hospitalBra = HospitalBra.ADAPTER.redact(builder.hospitalBra);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
