// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: SaasModel.proto at 719:1
package com.yijianyi.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class OrgTagItem extends Message<OrgTagItem, OrgTagItem.Builder> {
  public static final ProtoAdapter<OrgTagItem> ADAPTER = new ProtoAdapter_OrgTagItem();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_ID = 0L;

  public static final String DEFAULT_TAGNAME = "";

  public static final Integer DEFAULT_COLOR = 0;

  public static final String DEFAULT_COLORSTR = "";

  public static final Integer DEFAULT_STATE = 0;

  public static final Long DEFAULT_CREATESTAFFID = 0L;

  public static final String DEFAULT_CREATESTAFFNAME = "";

  public static final Long DEFAULT_CREATETIME = 0L;

  /**
   * id
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long id;

  /**
   * 标签名
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String tagName;

  /**
   * 标签颜色 1 #FFC362 2 #2BD6BD 3 #FD6565 4 #333333 5 #48A0DC
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer color;

  /**
   * 颜色字符串   eg:#FFC362
   */
  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String colorStr;

  /**
   * 状态 -1 已删除 0 正常
   */
  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer state;

  /**
   * 创建员工id
   */
  @WireField(
      tag = 6,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long createStaffId;

  /**
   * 创建员工姓名
   */
  @WireField(
      tag = 7,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String createStaffName;

  /**
   * 创建时间
   */
  @WireField(
      tag = 8,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long createTime;

  public OrgTagItem(Long id, String tagName, Integer color, String colorStr, Integer state, Long createStaffId, String createStaffName, Long createTime) {
    this(id, tagName, color, colorStr, state, createStaffId, createStaffName, createTime, ByteString.EMPTY);
  }

  public OrgTagItem(Long id, String tagName, Integer color, String colorStr, Integer state, Long createStaffId, String createStaffName, Long createTime, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.id = id;
    this.tagName = tagName;
    this.color = color;
    this.colorStr = colorStr;
    this.state = state;
    this.createStaffId = createStaffId;
    this.createStaffName = createStaffName;
    this.createTime = createTime;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.id = id;
    builder.tagName = tagName;
    builder.color = color;
    builder.colorStr = colorStr;
    builder.state = state;
    builder.createStaffId = createStaffId;
    builder.createStaffName = createStaffName;
    builder.createTime = createTime;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof OrgTagItem)) return false;
    OrgTagItem o = (OrgTagItem) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(id, o.id)
        && Internal.equals(tagName, o.tagName)
        && Internal.equals(color, o.color)
        && Internal.equals(colorStr, o.colorStr)
        && Internal.equals(state, o.state)
        && Internal.equals(createStaffId, o.createStaffId)
        && Internal.equals(createStaffName, o.createStaffName)
        && Internal.equals(createTime, o.createTime);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (id != null ? id.hashCode() : 0);
      result = result * 37 + (tagName != null ? tagName.hashCode() : 0);
      result = result * 37 + (color != null ? color.hashCode() : 0);
      result = result * 37 + (colorStr != null ? colorStr.hashCode() : 0);
      result = result * 37 + (state != null ? state.hashCode() : 0);
      result = result * 37 + (createStaffId != null ? createStaffId.hashCode() : 0);
      result = result * 37 + (createStaffName != null ? createStaffName.hashCode() : 0);
      result = result * 37 + (createTime != null ? createTime.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (id != null) builder.append(", id=").append(id);
    if (tagName != null) builder.append(", tagName=").append(tagName);
    if (color != null) builder.append(", color=").append(color);
    if (colorStr != null) builder.append(", colorStr=").append(colorStr);
    if (state != null) builder.append(", state=").append(state);
    if (createStaffId != null) builder.append(", createStaffId=").append(createStaffId);
    if (createStaffName != null) builder.append(", createStaffName=").append(createStaffName);
    if (createTime != null) builder.append(", createTime=").append(createTime);
    return builder.replace(0, 2, "OrgTagItem{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<OrgTagItem, Builder> {
    public Long id;

    public String tagName;

    public Integer color;

    public String colorStr;

    public Integer state;

    public Long createStaffId;

    public String createStaffName;

    public Long createTime;

    public Builder() {
    }

    /**
     * id
     */
    public Builder id(Long id) {
      this.id = id;
      return this;
    }

    /**
     * 标签名
     */
    public Builder tagName(String tagName) {
      this.tagName = tagName;
      return this;
    }

    /**
     * 标签颜色 1 #FFC362 2 #2BD6BD 3 #FD6565 4 #333333 5 #48A0DC
     */
    public Builder color(Integer color) {
      this.color = color;
      return this;
    }

    /**
     * 颜色字符串   eg:#FFC362
     */
    public Builder colorStr(String colorStr) {
      this.colorStr = colorStr;
      return this;
    }

    /**
     * 状态 -1 已删除 0 正常
     */
    public Builder state(Integer state) {
      this.state = state;
      return this;
    }

    /**
     * 创建员工id
     */
    public Builder createStaffId(Long createStaffId) {
      this.createStaffId = createStaffId;
      return this;
    }

    /**
     * 创建员工姓名
     */
    public Builder createStaffName(String createStaffName) {
      this.createStaffName = createStaffName;
      return this;
    }

    /**
     * 创建时间
     */
    public Builder createTime(Long createTime) {
      this.createTime = createTime;
      return this;
    }

    @Override
    public OrgTagItem build() {
      return new OrgTagItem(id, tagName, color, colorStr, state, createStaffId, createStaffName, createTime, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_OrgTagItem extends ProtoAdapter<OrgTagItem> {
    ProtoAdapter_OrgTagItem() {
      super(FieldEncoding.LENGTH_DELIMITED, OrgTagItem.class);
    }

    @Override
    public int encodedSize(OrgTagItem value) {
      return (value.id != null ? ProtoAdapter.UINT64.encodedSizeWithTag(1, value.id) : 0)
          + (value.tagName != null ? ProtoAdapter.STRING.encodedSizeWithTag(2, value.tagName) : 0)
          + (value.color != null ? ProtoAdapter.UINT32.encodedSizeWithTag(3, value.color) : 0)
          + (value.colorStr != null ? ProtoAdapter.STRING.encodedSizeWithTag(4, value.colorStr) : 0)
          + (value.state != null ? ProtoAdapter.UINT32.encodedSizeWithTag(5, value.state) : 0)
          + (value.createStaffId != null ? ProtoAdapter.UINT64.encodedSizeWithTag(6, value.createStaffId) : 0)
          + (value.createStaffName != null ? ProtoAdapter.STRING.encodedSizeWithTag(7, value.createStaffName) : 0)
          + (value.createTime != null ? ProtoAdapter.UINT64.encodedSizeWithTag(8, value.createTime) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, OrgTagItem value) throws IOException {
      if (value.id != null) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.id);
      if (value.tagName != null) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.tagName);
      if (value.color != null) ProtoAdapter.UINT32.encodeWithTag(writer, 3, value.color);
      if (value.colorStr != null) ProtoAdapter.STRING.encodeWithTag(writer, 4, value.colorStr);
      if (value.state != null) ProtoAdapter.UINT32.encodeWithTag(writer, 5, value.state);
      if (value.createStaffId != null) ProtoAdapter.UINT64.encodeWithTag(writer, 6, value.createStaffId);
      if (value.createStaffName != null) ProtoAdapter.STRING.encodeWithTag(writer, 7, value.createStaffName);
      if (value.createTime != null) ProtoAdapter.UINT64.encodeWithTag(writer, 8, value.createTime);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public OrgTagItem decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.id(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.tagName(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.color(ProtoAdapter.UINT32.decode(reader)); break;
          case 4: builder.colorStr(ProtoAdapter.STRING.decode(reader)); break;
          case 5: builder.state(ProtoAdapter.UINT32.decode(reader)); break;
          case 6: builder.createStaffId(ProtoAdapter.UINT64.decode(reader)); break;
          case 7: builder.createStaffName(ProtoAdapter.STRING.decode(reader)); break;
          case 8: builder.createTime(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public OrgTagItem redact(OrgTagItem value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
