// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: AppInterface.proto at 1448:1
package com.yijianyi.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * 获取订单夜陪服务信息
 */
public final class SaveOrUpdateOrderItemNighReq extends Message<SaveOrUpdateOrderItemNighReq, SaveOrUpdateOrderItemNighReq.Builder> {
  public static final ProtoAdapter<SaveOrUpdateOrderItemNighReq> ADAPTER = new ProtoAdapter_SaveOrUpdateOrderItemNighReq();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_ORDERID = "";

  public static final Long DEFAULT_PRICEID = 0L;

  public static final Long DEFAULT_ITEMID = 0L;

  public static final Long DEFAULT_HGID = 0L;

  public static final Integer DEFAULT_TYPE = 0;

  /**
   * 订单id
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String orderId;

  /**
   * 服务id
   */
  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long priceId;

  /**
   * 服务项id
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long itemId;

  /**
   * 护工id
   */
  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long hgId;

  /**
   * 操作类型 0- 创建夜陪服务 1- 删除夜陪服务 2-修改夜陪服务
   */
  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer type;

  public SaveOrUpdateOrderItemNighReq(String orderId, Long priceId, Long itemId, Long hgId, Integer type) {
    this(orderId, priceId, itemId, hgId, type, ByteString.EMPTY);
  }

  public SaveOrUpdateOrderItemNighReq(String orderId, Long priceId, Long itemId, Long hgId, Integer type, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.orderId = orderId;
    this.priceId = priceId;
    this.itemId = itemId;
    this.hgId = hgId;
    this.type = type;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.orderId = orderId;
    builder.priceId = priceId;
    builder.itemId = itemId;
    builder.hgId = hgId;
    builder.type = type;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SaveOrUpdateOrderItemNighReq)) return false;
    SaveOrUpdateOrderItemNighReq o = (SaveOrUpdateOrderItemNighReq) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(orderId, o.orderId)
        && Internal.equals(priceId, o.priceId)
        && Internal.equals(itemId, o.itemId)
        && Internal.equals(hgId, o.hgId)
        && Internal.equals(type, o.type);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (orderId != null ? orderId.hashCode() : 0);
      result = result * 37 + (priceId != null ? priceId.hashCode() : 0);
      result = result * 37 + (itemId != null ? itemId.hashCode() : 0);
      result = result * 37 + (hgId != null ? hgId.hashCode() : 0);
      result = result * 37 + (type != null ? type.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (orderId != null) builder.append(", orderId=").append(orderId);
    if (priceId != null) builder.append(", priceId=").append(priceId);
    if (itemId != null) builder.append(", itemId=").append(itemId);
    if (hgId != null) builder.append(", hgId=").append(hgId);
    if (type != null) builder.append(", type=").append(type);
    return builder.replace(0, 2, "SaveOrUpdateOrderItemNighReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<SaveOrUpdateOrderItemNighReq, Builder> {
    public String orderId;

    public Long priceId;

    public Long itemId;

    public Long hgId;

    public Integer type;

    public Builder() {
    }

    /**
     * 订单id
     */
    public Builder orderId(String orderId) {
      this.orderId = orderId;
      return this;
    }

    /**
     * 服务id
     */
    public Builder priceId(Long priceId) {
      this.priceId = priceId;
      return this;
    }

    /**
     * 服务项id
     */
    public Builder itemId(Long itemId) {
      this.itemId = itemId;
      return this;
    }

    /**
     * 护工id
     */
    public Builder hgId(Long hgId) {
      this.hgId = hgId;
      return this;
    }

    /**
     * 操作类型 0- 创建夜陪服务 1- 删除夜陪服务 2-修改夜陪服务
     */
    public Builder type(Integer type) {
      this.type = type;
      return this;
    }

    @Override
    public SaveOrUpdateOrderItemNighReq build() {
      return new SaveOrUpdateOrderItemNighReq(orderId, priceId, itemId, hgId, type, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_SaveOrUpdateOrderItemNighReq extends ProtoAdapter<SaveOrUpdateOrderItemNighReq> {
    ProtoAdapter_SaveOrUpdateOrderItemNighReq() {
      super(FieldEncoding.LENGTH_DELIMITED, SaveOrUpdateOrderItemNighReq.class);
    }

    @Override
    public int encodedSize(SaveOrUpdateOrderItemNighReq value) {
      return (value.orderId != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.orderId) : 0)
          + (value.priceId != null ? ProtoAdapter.UINT64.encodedSizeWithTag(2, value.priceId) : 0)
          + (value.itemId != null ? ProtoAdapter.UINT64.encodedSizeWithTag(3, value.itemId) : 0)
          + (value.hgId != null ? ProtoAdapter.UINT64.encodedSizeWithTag(4, value.hgId) : 0)
          + (value.type != null ? ProtoAdapter.UINT32.encodedSizeWithTag(5, value.type) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, SaveOrUpdateOrderItemNighReq value) throws IOException {
      if (value.orderId != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.orderId);
      if (value.priceId != null) ProtoAdapter.UINT64.encodeWithTag(writer, 2, value.priceId);
      if (value.itemId != null) ProtoAdapter.UINT64.encodeWithTag(writer, 3, value.itemId);
      if (value.hgId != null) ProtoAdapter.UINT64.encodeWithTag(writer, 4, value.hgId);
      if (value.type != null) ProtoAdapter.UINT32.encodeWithTag(writer, 5, value.type);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public SaveOrUpdateOrderItemNighReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.orderId(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.priceId(ProtoAdapter.UINT64.decode(reader)); break;
          case 3: builder.itemId(ProtoAdapter.UINT64.decode(reader)); break;
          case 4: builder.hgId(ProtoAdapter.UINT64.decode(reader)); break;
          case 5: builder.type(ProtoAdapter.UINT32.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public SaveOrUpdateOrderItemNighReq redact(SaveOrUpdateOrderItemNighReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
