// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: AppInterface.proto at 130:1
package com.yijianyi.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * 标记系统消息已读
 */
public final class SystemMsgMarkAsReadReq extends Message<SystemMsgMarkAsReadReq, SystemMsgMarkAsReadReq.Builder> {
  public static final ProtoAdapter<SystemMsgMarkAsReadReq> ADAPTER = new ProtoAdapter_SystemMsgMarkAsReadReq();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_ID = 0L;

  /**
   * 消息id
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long id;

  public SystemMsgMarkAsReadReq(Long id) {
    this(id, ByteString.EMPTY);
  }

  public SystemMsgMarkAsReadReq(Long id, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.id = id;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.id = id;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SystemMsgMarkAsReadReq)) return false;
    SystemMsgMarkAsReadReq o = (SystemMsgMarkAsReadReq) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(id, o.id);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (id != null ? id.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (id != null) builder.append(", id=").append(id);
    return builder.replace(0, 2, "SystemMsgMarkAsReadReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<SystemMsgMarkAsReadReq, Builder> {
    public Long id;

    public Builder() {
    }

    /**
     * 消息id
     */
    public Builder id(Long id) {
      this.id = id;
      return this;
    }

    @Override
    public SystemMsgMarkAsReadReq build() {
      return new SystemMsgMarkAsReadReq(id, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_SystemMsgMarkAsReadReq extends ProtoAdapter<SystemMsgMarkAsReadReq> {
    ProtoAdapter_SystemMsgMarkAsReadReq() {
      super(FieldEncoding.LENGTH_DELIMITED, SystemMsgMarkAsReadReq.class);
    }

    @Override
    public int encodedSize(SystemMsgMarkAsReadReq value) {
      return (value.id != null ? ProtoAdapter.UINT64.encodedSizeWithTag(1, value.id) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, SystemMsgMarkAsReadReq value) throws IOException {
      if (value.id != null) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.id);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public SystemMsgMarkAsReadReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.id(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public SystemMsgMarkAsReadReq redact(SystemMsgMarkAsReadReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
