// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: AppInterface.proto at 2048:1
package com.yijianyi.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * 转出订单
 */
public final class TransferInsureOrderReq extends Message<TransferInsureOrderReq, TransferInsureOrderReq.Builder> {
  public static final ProtoAdapter<TransferInsureOrderReq> ADAPTER = new ProtoAdapter_TransferInsureOrderReq();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_ORDERID = "";

  public static final Long DEFAULT_HGID = 0L;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String orderId;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long hgId;

  public TransferInsureOrderReq(String orderId, Long hgId) {
    this(orderId, hgId, ByteString.EMPTY);
  }

  public TransferInsureOrderReq(String orderId, Long hgId, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.orderId = orderId;
    this.hgId = hgId;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.orderId = orderId;
    builder.hgId = hgId;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof TransferInsureOrderReq)) return false;
    TransferInsureOrderReq o = (TransferInsureOrderReq) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(orderId, o.orderId)
        && Internal.equals(hgId, o.hgId);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (orderId != null ? orderId.hashCode() : 0);
      result = result * 37 + (hgId != null ? hgId.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (orderId != null) builder.append(", orderId=").append(orderId);
    if (hgId != null) builder.append(", hgId=").append(hgId);
    return builder.replace(0, 2, "TransferInsureOrderReq{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<TransferInsureOrderReq, Builder> {
    public String orderId;

    public Long hgId;

    public Builder() {
    }

    public Builder orderId(String orderId) {
      this.orderId = orderId;
      return this;
    }

    public Builder hgId(Long hgId) {
      this.hgId = hgId;
      return this;
    }

    @Override
    public TransferInsureOrderReq build() {
      return new TransferInsureOrderReq(orderId, hgId, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_TransferInsureOrderReq extends ProtoAdapter<TransferInsureOrderReq> {
    ProtoAdapter_TransferInsureOrderReq() {
      super(FieldEncoding.LENGTH_DELIMITED, TransferInsureOrderReq.class);
    }

    @Override
    public int encodedSize(TransferInsureOrderReq value) {
      return (value.orderId != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.orderId) : 0)
          + (value.hgId != null ? ProtoAdapter.UINT64.encodedSizeWithTag(2, value.hgId) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, TransferInsureOrderReq value) throws IOException {
      if (value.orderId != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.orderId);
      if (value.hgId != null) ProtoAdapter.UINT64.encodeWithTag(writer, 2, value.hgId);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public TransferInsureOrderReq decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.orderId(ProtoAdapter.STRING.decode(reader)); break;
          case 2: builder.hgId(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public TransferInsureOrderReq redact(TransferInsureOrderReq value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
