// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: SaasModel.proto at 476:1
package com.yijianyi.protocol;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class UserAccountRecord extends Message<UserAccountRecord, UserAccountRecord.Builder> {
  public static final ProtoAdapter<UserAccountRecord> ADAPTER = new ProtoAdapter_UserAccountRecord();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_ID = 0L;

  public static final Long DEFAULT_USERID = 0L;

  public static final Long DEFAULT_COMPANYID = 0L;

  public static final Long DEFAULT_CHANGEACCOUNT = 0L;

  public static final Long DEFAULT_ACCOUNT = 0L;

  public static final Integer DEFAULT_CHANGETYPE = 0;

  public static final String DEFAULT_CHANGEDESC = "";

  public static final String DEFAULT_ORDERID = "";

  public static final Long DEFAULT_CREATETIME = 0L;

  public static final String DEFAULT_REMARK = "";

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long id;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long userId;

  /**
   * 公司id
   */
  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long companyId;

  /**
   * 变动的金额
   */
  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long changeAccount;

  /**
   * 剩余账户金额
   */
  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long account;

  /**
   * 账户变动类型 1-充值 2-消费 3-体现 4-订单余额退回 5-充值赠送 6-保证金退还 7-补贴金转余额  8-提现失败退还 9-订单取消预付金退还
   */
  @WireField(
      tag = 6,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32"
  )
  public final Integer changeType;

  /**
   * 账户变动原因
   */
  @WireField(
      tag = 7,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String changeDesc;

  /**
   * 消费或订单余额退回时涉及到的订单id
   */
  @WireField(
      tag = 8,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String orderId;

  /**
   * 创建时间
   */
  @WireField(
      tag = 9,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long createTime;

  /**
   * 备注
   */
  @WireField(
      tag = 10,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String remark;

  public UserAccountRecord(Long id, Long userId, Long companyId, Long changeAccount, Long account, Integer changeType, String changeDesc, String orderId, Long createTime, String remark) {
    this(id, userId, companyId, changeAccount, account, changeType, changeDesc, orderId, createTime, remark, ByteString.EMPTY);
  }

  public UserAccountRecord(Long id, Long userId, Long companyId, Long changeAccount, Long account, Integer changeType, String changeDesc, String orderId, Long createTime, String remark, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.id = id;
    this.userId = userId;
    this.companyId = companyId;
    this.changeAccount = changeAccount;
    this.account = account;
    this.changeType = changeType;
    this.changeDesc = changeDesc;
    this.orderId = orderId;
    this.createTime = createTime;
    this.remark = remark;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.id = id;
    builder.userId = userId;
    builder.companyId = companyId;
    builder.changeAccount = changeAccount;
    builder.account = account;
    builder.changeType = changeType;
    builder.changeDesc = changeDesc;
    builder.orderId = orderId;
    builder.createTime = createTime;
    builder.remark = remark;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof UserAccountRecord)) return false;
    UserAccountRecord o = (UserAccountRecord) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(id, o.id)
        && Internal.equals(userId, o.userId)
        && Internal.equals(companyId, o.companyId)
        && Internal.equals(changeAccount, o.changeAccount)
        && Internal.equals(account, o.account)
        && Internal.equals(changeType, o.changeType)
        && Internal.equals(changeDesc, o.changeDesc)
        && Internal.equals(orderId, o.orderId)
        && Internal.equals(createTime, o.createTime)
        && Internal.equals(remark, o.remark);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (id != null ? id.hashCode() : 0);
      result = result * 37 + (userId != null ? userId.hashCode() : 0);
      result = result * 37 + (companyId != null ? companyId.hashCode() : 0);
      result = result * 37 + (changeAccount != null ? changeAccount.hashCode() : 0);
      result = result * 37 + (account != null ? account.hashCode() : 0);
      result = result * 37 + (changeType != null ? changeType.hashCode() : 0);
      result = result * 37 + (changeDesc != null ? changeDesc.hashCode() : 0);
      result = result * 37 + (orderId != null ? orderId.hashCode() : 0);
      result = result * 37 + (createTime != null ? createTime.hashCode() : 0);
      result = result * 37 + (remark != null ? remark.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (id != null) builder.append(", id=").append(id);
    if (userId != null) builder.append(", userId=").append(userId);
    if (companyId != null) builder.append(", companyId=").append(companyId);
    if (changeAccount != null) builder.append(", changeAccount=").append(changeAccount);
    if (account != null) builder.append(", account=").append(account);
    if (changeType != null) builder.append(", changeType=").append(changeType);
    if (changeDesc != null) builder.append(", changeDesc=").append(changeDesc);
    if (orderId != null) builder.append(", orderId=").append(orderId);
    if (createTime != null) builder.append(", createTime=").append(createTime);
    if (remark != null) builder.append(", remark=").append(remark);
    return builder.replace(0, 2, "UserAccountRecord{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<UserAccountRecord, Builder> {
    public Long id;

    public Long userId;

    public Long companyId;

    public Long changeAccount;

    public Long account;

    public Integer changeType;

    public String changeDesc;

    public String orderId;

    public Long createTime;

    public String remark;

    public Builder() {
    }

    public Builder id(Long id) {
      this.id = id;
      return this;
    }

    public Builder userId(Long userId) {
      this.userId = userId;
      return this;
    }

    /**
     * 公司id
     */
    public Builder companyId(Long companyId) {
      this.companyId = companyId;
      return this;
    }

    /**
     * 变动的金额
     */
    public Builder changeAccount(Long changeAccount) {
      this.changeAccount = changeAccount;
      return this;
    }

    /**
     * 剩余账户金额
     */
    public Builder account(Long account) {
      this.account = account;
      return this;
    }

    /**
     * 账户变动类型 1-充值 2-消费 3-体现 4-订单余额退回 5-充值赠送 6-保证金退还 7-补贴金转余额  8-提现失败退还 9-订单取消预付金退还
     */
    public Builder changeType(Integer changeType) {
      this.changeType = changeType;
      return this;
    }

    /**
     * 账户变动原因
     */
    public Builder changeDesc(String changeDesc) {
      this.changeDesc = changeDesc;
      return this;
    }

    /**
     * 消费或订单余额退回时涉及到的订单id
     */
    public Builder orderId(String orderId) {
      this.orderId = orderId;
      return this;
    }

    /**
     * 创建时间
     */
    public Builder createTime(Long createTime) {
      this.createTime = createTime;
      return this;
    }

    /**
     * 备注
     */
    public Builder remark(String remark) {
      this.remark = remark;
      return this;
    }

    @Override
    public UserAccountRecord build() {
      return new UserAccountRecord(id, userId, companyId, changeAccount, account, changeType, changeDesc, orderId, createTime, remark, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_UserAccountRecord extends ProtoAdapter<UserAccountRecord> {
    ProtoAdapter_UserAccountRecord() {
      super(FieldEncoding.LENGTH_DELIMITED, UserAccountRecord.class);
    }

    @Override
    public int encodedSize(UserAccountRecord value) {
      return (value.id != null ? ProtoAdapter.UINT64.encodedSizeWithTag(1, value.id) : 0)
          + (value.userId != null ? ProtoAdapter.UINT64.encodedSizeWithTag(2, value.userId) : 0)
          + (value.companyId != null ? ProtoAdapter.UINT64.encodedSizeWithTag(3, value.companyId) : 0)
          + (value.changeAccount != null ? ProtoAdapter.INT64.encodedSizeWithTag(4, value.changeAccount) : 0)
          + (value.account != null ? ProtoAdapter.UINT64.encodedSizeWithTag(5, value.account) : 0)
          + (value.changeType != null ? ProtoAdapter.UINT32.encodedSizeWithTag(6, value.changeType) : 0)
          + (value.changeDesc != null ? ProtoAdapter.STRING.encodedSizeWithTag(7, value.changeDesc) : 0)
          + (value.orderId != null ? ProtoAdapter.STRING.encodedSizeWithTag(8, value.orderId) : 0)
          + (value.createTime != null ? ProtoAdapter.UINT64.encodedSizeWithTag(9, value.createTime) : 0)
          + (value.remark != null ? ProtoAdapter.STRING.encodedSizeWithTag(10, value.remark) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, UserAccountRecord value) throws IOException {
      if (value.id != null) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.id);
      if (value.userId != null) ProtoAdapter.UINT64.encodeWithTag(writer, 2, value.userId);
      if (value.companyId != null) ProtoAdapter.UINT64.encodeWithTag(writer, 3, value.companyId);
      if (value.changeAccount != null) ProtoAdapter.INT64.encodeWithTag(writer, 4, value.changeAccount);
      if (value.account != null) ProtoAdapter.UINT64.encodeWithTag(writer, 5, value.account);
      if (value.changeType != null) ProtoAdapter.UINT32.encodeWithTag(writer, 6, value.changeType);
      if (value.changeDesc != null) ProtoAdapter.STRING.encodeWithTag(writer, 7, value.changeDesc);
      if (value.orderId != null) ProtoAdapter.STRING.encodeWithTag(writer, 8, value.orderId);
      if (value.createTime != null) ProtoAdapter.UINT64.encodeWithTag(writer, 9, value.createTime);
      if (value.remark != null) ProtoAdapter.STRING.encodeWithTag(writer, 10, value.remark);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public UserAccountRecord decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.id(ProtoAdapter.UINT64.decode(reader)); break;
          case 2: builder.userId(ProtoAdapter.UINT64.decode(reader)); break;
          case 3: builder.companyId(ProtoAdapter.UINT64.decode(reader)); break;
          case 4: builder.changeAccount(ProtoAdapter.INT64.decode(reader)); break;
          case 5: builder.account(ProtoAdapter.UINT64.decode(reader)); break;
          case 6: builder.changeType(ProtoAdapter.UINT32.decode(reader)); break;
          case 7: builder.changeDesc(ProtoAdapter.STRING.decode(reader)); break;
          case 8: builder.orderId(ProtoAdapter.STRING.decode(reader)); break;
          case 9: builder.createTime(ProtoAdapter.UINT64.decode(reader)); break;
          case 10: builder.remark(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public UserAccountRecord redact(UserAccountRecord value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
